### ISSUE TITLE
上边的展示在第一项滑动到第二项时,会直接跳到第四项

### ISSUE THREAD

**Issue by caleucheg** [xmuSistone/android-pile-layout#2]

**Comment by xmuSistone** [comment]
怎么出现的呢？能否详细一些

**Comment by caleucheg** [comment]
没有什么其他操作,就是在第一页滑动上方图片时,动画过后,会直接跳到第四页,

**Comment by xmuSistone** [comment]
滑动距离过长的话，是有可能直接从第一项到第三项的；至于到了第四项，我不大清楚为什么，我这边也没遇到这种情况。如果有必现的方法，可在此issue下留言。

**Comment by caleucheg** [comment]
我开始也想可能是滑动距离的问题,但是测试了一下滑动很小的距离也会发生.

**Comment by xmuSistone** [comment]
可是我这边一直没有这种情况；你安装下最新的Apk试试~老的Apk是默认有2.5个item，新的已经改成1.5个了，跟截图完全不一样了。

**Comment by caleucheg** [comment]
我测试了一下是个别机型有这个问题,我这里有一台测试机型是华为的会出现

**Comment by xmuSistone** [comment]
嗯好的。后面我也用其它手机测下
