### ISSUE TITLE
滑动无法像ViewPager一样取消

### ISSUE THREAD

**Issue by kylin17** [xmuSistone/android-pile-layout#3]
如题，往左或往右滑动某一项时，如果不松手恢复到接近原来的位置再松手，还是会触发滑动项的移动，无法复原原来的位置。是否可以考虑根据滑动项移动的比例来决定是否滑动到下一项或是复原原来的位置?

**Comment by xmuSistone** [comment]
可以的。之前出于一切从简的考虑，代码没有写的太细致，后面我有时间优化一下。

**Comment by xmuSistone** [comment]
@kylin17 已加入位移和速度的考量，代码已提交，可更新代码试下
