### ISSUE TITLE
Fix this bug

### ISSUE THREAD

**Issue by tellfa** [xmuSistone/android-pile-layout#4]
Hi, Thanks for this library. When scroll images, some times show me this bug.
please see this image, and i highlight bugs
![capture _2017-05-23-12-00-15](https://cloud.githubusercontent.com/assets/10583945/26345406/0fbc8000-3fb8-11e7-8f4a-d74966b9cf7a.png)

can you fix this bug?

**Comment by xmuSistone** [comment]
Hello, while the bitmap is downloading or failed, the imageview needs a default image. So, u can fix this bug by passing a default image source file to glide.
