### ISSUE TITLE
  请问下 如何把第一张的位置放到中间呢？

### ISSUE THREAD

**Issue by 1184104588** [xmuSistone/android-pile-layout#9]
如题

**Comment by xmuSistone** [comment]
放在中间的处理，交互逻辑让人猜不透。如果你不介怀的话，可以这么考量：你把recyclerView的高度设置成屏幕高度的一半，这样看起来，第一个itemView缩放隐藏的，差不多刚好就在中间位置。

**Comment by xmuSistone** [comment]
暂时不支持这个的了
